id: hl7-to-json-channel
name: HL7 MLLP to JSON Converter
description: Receives HL7 messages via MLLP and converts them to JSON format
enabled: true

source:
  type: hl7_mllp
  config:
    host: 0.0.0.0
    port: 2575

transformers:
  - type: hl7_to_json
    config:
      pretty_print: true

destinations:
  - type: console
    config:
      pretty_print: true

  - type: json_file
    config:
      directory: ./output
      pretty_print: true

error_handling:
  on_error: continue  # continue, stop, retry
  retry_attempts: 3
  retry_delay: 5s

performance:
  workers: 4
  batch_size: 10
  buffer_size: 100
