sources:
    -   type: "postgres"
        key: "prod-db"
        host: "localhost"
        port: 5432
        driver: "postgres"
        username: "postgres"
        password: "postgres"
        database: "clear_dev"
        disablelogger: true

destination:
    type: "json"
    file: "charge_master.json"

checkpoint:
    file: "checkpoint.txt"
    field: "id"

tables:
    -   old_name: "charge_master"
        migrate: true
        clone_source: false
        batch_size: 10000
        update_sequence: true
        skip_store_error: true
        truncate_destination: true
        mapping:
            id: "charge_master_id"
            work_item_id: "work_item_id"
            cpt_hcpcs_code: "cpt_hcpcs_code"
            client_proc_esc: "client_proc_esc"
            client_internal_code: "client_internal_code"
            charge_amt: "charge_amt"
            charge_type: "charge_type"
            physician_category: "physician_category"
            created_at: "eval.{{now()}}"
            updated_at: "eval.{{now()}}"
            status: "eval.{{'ACTIVE'}}"
            is_active: "eval.{{true}}"