sources:
    - type: "csv"
      file: "providers.csv"
    - type: "json"
      file: "providers.json"
    - type: "postgresql"
      host: "localhost"
      port: 5432
      username: "postgres"
      password: "postgres"
      driver: "postgres"
      database: "mydb"
      source: "SELECT * FROM providers_sql"

destination:
    type: "json"
    file: "output.json"

lookups:
    - type: "csv"
      file: "users.csv"
      key: "users"
    - type: "csv"
      file: "facilities.csv"
      key: "facilities"

tables:
    - clone_source: true
      migrate: true
      batch_size: 100
      truncate_destination: true
      auto_create_table: true
      mapping:
          id: "id"
          facility_id: "eval.{{lookupIn('facilities', 'facility_name', facility, 'id')}}"
          user_id: "eval.{{lookupIn('users', 'email', user_email, 'id')}}"
          is_active: "is_active"